
-- Tao database --
DROP DATABASE IF EXISTS -- ;
CREATE DATABASE -- ;
USE -- ;

DROP TABLE IF EXISTS -- ;
CREATE TABLE -- (
TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY

FOREIGN KEY(--) REFERENCES --(--) ON DELETE CASCADE,
FOREIGN KEY(--) REFERENCES --(--) ON DELETE CASCADE
);

-- INSERT du lieu vao bang --
INSERT INTO () VALUES
;

-- PROCEDURE: Ham, thu tuc, store --
DROP PROCEDURE IF EXISTS -- ;
DELIMITER $$
CREATE PROCEDURE -- ()
BEGIN


					
END$$
DELIMITER ;

Set @v_ = 0;
call  -- (--);
SELECT @v_;

-- trigger --
DROP TRIGGER IF EXISTS--;
DELIMITER $$
CREATE TRIGGER --
BEFORE -- ON --
FOR EACH ROW
BEGIN 
	IF NEW. -- THEN
		SIGNAL SQLSTATE '12345' 
		SET MESSAGE_TEXT='Ngay bi loi';
        
	END IF;

END $$
DELIMITER ;
